models:
  ocr_model:
    model_path: models/ocr_model.xml
    model_input_height: 96
    model_input_width: 416
    character_list: ['blank', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    max_len: 13
  segmentation_model:
    model_path: models/segmentation_model.xml
    model_input_height: 224
    model_input_width: 224
    min_area_for_detection: 100
    threshold: 0.5